---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: docker:git
  commands:
    - git fetch --tags

- name: test
  image: golang:1.14
  volumes:
    - name: deps
      path: /go
  commands:
  - make test-coverage

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
  when:
    branch:
    - master

- name: release
  image: golang:1.14
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
    - name: deps
      path: /go
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag

- name: docker-kubers-agent
  image: plugins/docker
  environment:
    VERSION: "${DRONE_TAG}"
  settings:
    repo: jacops/kubers-agent
    auto_tag: true
    dockerfile: cmd/kubers-agent/release.Dockerfile
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
    build_args_from_env:
      - VERSION
  when:
    event: tag
  depends_on:
    - release

- name: docker-kubersd
  image: plugins/docker
  environment:
    VERSION: "${DRONE_TAG}"
  settings:
    repo: jacops/kubersd
    auto_tag: true
    dockerfile: cmd/kubersd/release.Dockerfile
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
    build_args_from_env:
      - VERSION
  when:
    event: tag
  depends_on:
    - release

volumes:
  - name: deps
    temp: {}
