# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- id: kubersd
  binary: kubersd
  dir: cmd/kubersd
  ldflags:
  - -X main.version={{.Version}}
  flags:
  - -i
  - -v
  env:
  - CGO_ENABLED=0
- id: kubers-agent
  binary: kubers-agent
  dir: cmd/kubers-agent
  ldflags:
  - -X main.version={{.Version}}
  flags:
  - -i
  - -v
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - kubersd
    image_templates:
    - "jacops/kubersd:latest"
    - "jacops/kubersd:{{ .Tag }}"
    dockerfile: docker/Dockerfile.kubersd
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: amd64
    binaries:
    - kubers-agent
    image_templates:
    - "jacops/kubers-agent:latest"
    - "jacops/kubers-agent:{{ .Tag }}"
    dockerfile: docker/Dockerfile.kubers-agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
