apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubers.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kubers.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "kubers.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kubers.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "kubers.name" . }}
    spec:
      serviceAccountName: {{ template "kubers.injector.serviceAccountName" . }}
      containers:
        - name: kubers
          image: "{{ .Values.injector.image.repository }}:{{ .Values.injector.image.tag }}"
          imagePullPolicy: {{ .Values.injector.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERSD_LISTEN
              value: ":{{ .Values.injector.webhook.port }}"
            - name: KUBERSD_LOG_LEVEL
              value: "{{ .Values.injector.log.level }}"
            - name: KUBERSD_AGENT_IMAGE
              value: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
            - name: KUBERSD_LOG_FORMAT
              value: "{{ .Values.injector.log.format }}"
            {{- if .Values.injector.webhook.tls.auto }}
            - name: KUBERSD_TLS_AUTO
              value: {{ template "kubers.fullname" . }}-cfg
            - name: KUBERSD_TLS_AUTO_HOSTS
              value: "{{ template "kubers.serviceName" . }},{{ template "kubers.serviceName" . }}.$(NAMESPACE),{{ template "kubers.serviceName" . }}.$(NAMESPACE).svc"
            {{- end }}
            {{- if .Values.injector.webhook.tls.certFile }}
            - name: KUBERSD_TLS_CERT_FILE
              value: {{ .Values.injector.webhook.tls.certFile }}
            {{- end }}
            {{- if .Values.injector.webhook.tls.keyFile }}
            - name: KUBERSD_TLS_KEY_FILE
              value: {{ .Values.injector.webhook.tls.keyFile }}
            {{- end }}
            {{- if .Values.agent.log.format }}
            - name: KUBERS_AGENT_LOG_FORMAT
              value: {{ .Values.agent.log.format }}
            {{- end }}
            {{- if .Values.agent.log.level }}
            - name: KUBERS_AGENT_LOG_LEVEL
              value: {{ .Values.agent.log.level }}
            {{- end }}
            {{- if .Values.agent.provider.name }}
            - name: KUBERS_AGENT_PROVIDER
              value: {{ .Values.agent.provider.name }}
            {{- end }}
            {{- if .Values.agent.provider.aws.region }}
            - name: KUBERS_AGENT_PROVIDER_AWS_REGION
              value: {{ .Values.agent.aws.region }}
            {{- end }}
          args:
            - webhook
            - 2>&1
