apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubers.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kubers.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "kubers.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kubers.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "kubers.name" . }}
    spec:
      serviceAccountName: {{ template "kubers.injector.serviceAccountName" . }}
      containers:
        - name: kubers
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AGENT_INJECT_LISTEN
              value: ":8080"
            - name: AGENT_INJECT_LOG_LEVEL
              value: "debug"
            - name: AGENT_INJECT_LOG_FORMAT
              value: "standard"
            - name: AGENT_INJECT_TLS_AUTO
              value: kubers-cfg
            - name: AGENT_INJECT_TLS_AUTO_HOSTS
              value: "{{ template "kubers.serviceName" . }},{{ template "kubers.serviceName" . }}.$(NAMESPACE),{{ template "kubers.serviceName" . }}.$(NAMESPACE).svc"
          args:
            - injector
            - admission-server
            - 2>&1
