FROM alpine:latest

ENV KUBERSCTL_BIN=/usr/local/bin/kubers-agent \
    USER_NAME=kubers-agent

RUN mkdir /licenses
COPY LICENSE /licenses

RUN set -ex && \
    addgroup -S ${USER_NAME} && \
    adduser -S --no-create-home -G ${USER_NAME} --disabled-password ${USER_NAME}

# switch to non-root user
USER ${USER_NAME}

COPY dist/kubers-agent ${KUBERSCTL_BIN}

ENTRYPOINT ["/usr/local/bin/kubers-agent"]
