---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubers
  labels:
    app.kubernetes.io/name: kubers
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubers
    spec:
      serviceAccountName: "kubers"
      containers:
        - name: kubers
          image: jacops/kubersd:v0.2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AGENT_INJECT_LISTEN
              value: ":8080"
            - name: AGENT_INJECT_LOG_LEVEL
              value: "debug"
            - name: AGENT_INJECT_LOG_FORMAT
              value: "standard"
            - name: AGENT_INJECT_TLS_AUTO
              value: kubers-cfg
            - name: AGENT_INJECT_TLS_AUTO_HOSTS
              value: "webhook,webhook.$(NAMESPACE),webhook.$(NAMESPACE).svc"
          args:
            - webhook
            - 2>&1
