apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubers
  labels:
    app.kubernetes.io/name: kubers

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubers-clusterrole
  labels:
    app.kubernetes.io/name: kubers
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubers-binding
  labels:
    app.kubernetes.io/name: kubers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubers-clusterrole
subjects:
  - kind: ServiceAccount
    name: kubers
    namespace: kubers-agent-injector
